# Generated by Django 5.2.10 on 2026-02-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
